---
title: "appendix"
author: "Zeyu Hu"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
library(igraph)
library(tidyverse)
library(sf)
library(geojsonio)
```

## Appendix Figrue S2
```{r echo=FALSE}
data_dir <- "../data/"
years <- 2022:2022
file_list <- paste0(data_dir, "network_", years, ".csv")

seoul_map <- geojson_read("../data/skorea-submunicipalities-2018-topo.json", what = "sp")
seoul_map_11 <- st_as_sf(seoul_map[substr(seoul_map@data$code, 1, 2) == "11", ])
seoul_map_11 <- seoul_map_11 %>% mutate(gu = substr(code, 1, 4))
gu_boundaries <- seoul_map_11 %>%
  group_by(gu) %>%
  summarise(geometry = st_union(geometry))
gu_boundaries_lines <- st_cast(gu_boundaries, "MULTILINESTRING")


community_colors <- c(
  "1" = "#d35f00", "2" = "#fd7c1a", "3" = "#fcff07", "4" = "#fe9376",
  "5" = "#f3dee0", "6" = "#ffbd15", "7" = "#a0c9e5", "8" = "#1d9bf7",
  "9" = "#303cf9", "10" = "#b4403e", "11" = "#603c87", "12" = "black"
)
for (i in seq_along(years)) {
  year <- years[i]
  df <- read.csv(file_list[i])
  colnames(df) <- c("source", "target", "weight")
  
  g <- graph_from_data_frame(df, directed = TRUE)
  
  # Infomap 
  infomap_community <- cluster_infomap(g)
  community_membership <- membership(infomap_community)
  
  # reorder community by number of dongs
  membership_df <- data.frame(node = names(community_membership), community = community_membership)
  community_sizes <- membership_df %>%
    group_by(community) %>%
    summarise(size = n()) %>%
    arrange(desc(size)) %>%
    mutate(new_community = row_number())
  membership_df <- membership_df %>%
    left_join(community_sizes, by = "community") %>%
    mutate(community = new_community) %>%
    dplyr::select(-new_community)
  community_membership <- setNames(membership_df$community, membership_df$node)
  
  map_data <- seoul_map_11 %>%
    left_join(data.frame(code = names(community_membership),
                         community = as.factor(community_membership)),
              by = c("code" = "code"))
  
  community_map <- ggplot() +
    geom_sf(data = map_data, aes(fill = community), color = "grey", size = 0.2) +
    geom_sf(data = gu_boundaries_lines, color = "black", size = 1.5) +
    scale_fill_manual(values = community_colors) +
    theme_minimal() +
    theme(
      legend.position = "bottom",
      legend.box = "horizontal",
      panel.border = element_rect(color = "black", fill = NA, size = 1),
      plot.background = element_rect(fill = "white", color = NA)
    ) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE))
  
  # ggsave(
  #   filename = paste0("../result/Figure S2. ", year, ".png"),
  #   plot = community_map,
  #   width = 8, height = 6, dpi = 300, bg = "white"
  # )
}
```

